# Generated by Django 2.0.6 on 2018-06-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websurvey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyauth',
            name='id',
        ),
        migrations.AlterField(
            model_name='surveyauth',
            name='key',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
