# Generated by Django 2.0.6 on 2018-06-06 15:19

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('websurvey', '0002_auto_20180605_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveySubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyJSON', django_mysql.models.JSONField(default=dict)),
            ],
        ),
    ]
